version: '3'
services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - rabbitmq-network

  nodejs-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq-network

networks:
  rabbitmq-network:
