version: "3"
services:
  nest-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    volumes:
      - .:/home/app
    environment:
      NODE_ENV: "PRODUCTION"
    restart: always
